import random

from selenium.webdriver.common.by import By
class DemoblazePageLocators:
    index=random.randint(1, 9)
    index2=random.randint(3, 8)
    sidebar_index  = random.choice(["Phones", "Laptops", "Monitors"])
    NAVBAR_ID_LOGO = (By.CSS_SELECTOR, "#nava")
    SIGN_UP_BUTTON = (By.CSS_SELECTOR, "#signin2")
    LOGIN_BUTTON = (By.CSS_SELECTOR, "#login2")
    LOGIN_FORM_BUTTON = (By.CSS_SELECTOR, "button[onclick='logIn()']")
    REGISTER_BUTTON = (By.CSS_SELECTOR, "button[onclick='register()']")
    LOGIN_USERNAME = (By.CSS_SELECTOR, "#loginusername")
    LOGIN_PASSWORD = (By.CSS_SELECTOR, "#loginpassword")

    USERNAME_FIELD = (By.XPATH, "//input[@id='sign-username']")
    PASSWORLD_FIELD = (By.XPATH, "//input[@id='sign-password']")
    WELCOME_USERNAME_FIELD = (By.XPATH, "//a[@id='nameofuser']")
    PRODUCTS_CARDS = (By.XPATH,"(//div[@class='card h-100'])")
    PRODUCTS_CARDS2 = (By.XPATH, f"(//div[@class='col-lg-4 col-md-6 mb-4'])[{index}]")
    PRODUCTS_CARDS3 =  (By.XPATH, f"(//div[@class='col-lg-4 col-md-6 mb-4'])[{index2}]")
    CART_BUTTON = (By.XPATH,"//a[normalize-space()='Cart']")
    PRICE_INFO =(By.XPATH, "//div[@class='panel panel-info']")
    NEXT_BUTTON = (By.CSS_SELECTOR, "#next2")
    BUY_BUTTON = (By.XPATH,"//a[normalize-space()='Add to cart']")
    PRICE = (By.CSS_SELECTOR, ".price-container")
    SIDE_BAR =  (By.XPATH, f"(//a[normalize-space()='{sidebar_index}'])[1]")
    CONTACT = (By.XPATH, "//a[normalize-space()='Contact']")
    CONTACT_EMAIL = (By.CSS_SELECTOR, "#recipient-email")
    CONTACT_NAME = (By.CSS_SELECTOR, "#recipient-name")
    MESSAGE = (By.CSS_SELECTOR, "#message-text")
    SEND_MESSAGE = (By.CSS_SELECTOR, "button[onclick='send()']")
    ABOUT_US= (By.XPATH,"//a[normalize-space()='About us']")
    VIDEO= (By.XPATH,"//div[@class='vjs-poster']")
